# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VehicleMovement/GlobalPosEst.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VehicleMovement/GlobalPosEst.proto',
  package='pb',
  syntax='proto2',
  serialized_pb=_b('\n\"VehicleMovement/GlobalPosEst.proto\x12\x02pb\x1a\x0cheader.proto\"\xb4\x02\n\x0cGlobalPosEst\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12#\n\x04mode\x18\x12 \x01(\x0e\x32\x15.pb.GlobalPosEst.Mode\x12\x0c\n\x04mLat\x18\x06 \x01(\x01\x12\x0c\n\x04mLon\x18\x07 \x01(\x01\x12\x0f\n\x07mCourse\x18\x08 \x01(\x02\x12\x13\n\x0bmConfCircle\x18\n \x01(\x02\x12\x11\n\tmVelocity\x18\r \x01(\x02\x12\x10\n\x08mYawrate\x18\x0e \x01(\x02\x12\x10\n\x08mAccLong\x18\x0f \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x11 \x01(\x02\"X\n\x04Mode\x12\t\n\x05UNDEF\x10\x00\x12\x0c\n\x08GPS_ONLY\x10\x01\x12\x11\n\rVEHICLE_MODEL\x10\x02\x12\x08\n\x04\x44GPS\x10\x03\x12\r\n\tRTK_FLOAT\x10\x04\x12\x0b\n\x07RTK_INT\x10\x05')
  ,
  dependencies=[header__pb2.DESCRIPTOR,])



_GLOBALPOSEST_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='pb.GlobalPosEst.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPS_ONLY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_MODEL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DGPS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTK_FLOAT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTK_INT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=277,
  serialized_end=365,
)
_sym_db.RegisterEnumDescriptor(_GLOBALPOSEST_MODE)


_GLOBALPOSEST = _descriptor.Descriptor(
  name='GlobalPosEst',
  full_name='pb.GlobalPosEst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.GlobalPosEst.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='pb.GlobalPosEst.mode', index=1,
      number=18, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mLat', full_name='pb.GlobalPosEst.mLat', index=2,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mLon', full_name='pb.GlobalPosEst.mLon', index=3,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mCourse', full_name='pb.GlobalPosEst.mCourse', index=4,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mConfCircle', full_name='pb.GlobalPosEst.mConfCircle', index=5,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mVelocity', full_name='pb.GlobalPosEst.mVelocity', index=6,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mYawrate', full_name='pb.GlobalPosEst.mYawrate', index=7,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mAccLong', full_name='pb.GlobalPosEst.mAccLong', index=8,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='pb.GlobalPosEst.altitude', index=9,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GLOBALPOSEST_MODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=365,
)

_GLOBALPOSEST.fields_by_name['header'].message_type = header__pb2._HEADER
_GLOBALPOSEST.fields_by_name['mode'].enum_type = _GLOBALPOSEST_MODE
_GLOBALPOSEST_MODE.containing_type = _GLOBALPOSEST
DESCRIPTOR.message_types_by_name['GlobalPosEst'] = _GLOBALPOSEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalPosEst = _reflection.GeneratedProtocolMessageType('GlobalPosEst', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALPOSEST,
  __module__ = 'VehicleMovement.GlobalPosEst_pb2'
  # @@protoc_insertion_point(class_scope:pb.GlobalPosEst)
  ))
_sym_db.RegisterMessage(GlobalPosEst)


# @@protoc_insertion_point(module_scope)
