# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/BaseImage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorNearData/BaseImage.proto',
  package='pb.SensorNearData',
  syntax='proto2',
  serialized_pb=_b('\n\x1eSensorNearData/BaseImage.proto\x12\x11pb.SensorNearData\"u\n\tBaseImage\x12\x10\n\x05width\x18\x64 \x01(\r:\x01\x30\x12\x12\n\x06height\x18\xc8\x01 \x01(\r:\x01\x30\x12\x18\n\x0c\x62itsPerPixel\x18\xac\x02 \x01(\r:\x01\x38\x12\x14\n\x08\x64\x61taSize\x18\xa0\x06 \x01(\r:\x01\x30\x12\x12\n\timageData\x18\x84\x07 \x01(\x0c')
)




_BASEIMAGE = _descriptor.Descriptor(
  name='BaseImage',
  full_name='pb.SensorNearData.BaseImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='pb.SensorNearData.BaseImage.width', index=0,
      number=100, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='pb.SensorNearData.BaseImage.height', index=1,
      number=200, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitsPerPixel', full_name='pb.SensorNearData.BaseImage.bitsPerPixel', index=2,
      number=300, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=8,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataSize', full_name='pb.SensorNearData.BaseImage.dataSize', index=3,
      number=800, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='pb.SensorNearData.BaseImage.imageData', index=4,
      number=900, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['BaseImage'] = _BASEIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseImage = _reflection.GeneratedProtocolMessageType('BaseImage', (_message.Message,), dict(
  DESCRIPTOR = _BASEIMAGE,
  __module__ = 'SensorNearData.BaseImage_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorNearData.BaseImage)
  ))
_sym_db.RegisterMessage(BaseImage)


# @@protoc_insertion_point(module_scope)
