# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/VehicleDynamics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from SensorNearData import SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorNearData/VehicleDynamics.proto',
  package='pb.SensorNearData',
  syntax='proto2',
  serialized_pb=_b('\n$SensorNearData/VehicleDynamics.proto\x12\x11pb.SensorNearData\x1a\x0cheader.proto\x1a!SensorNearData/SensorStates.proto\"\x98\x05\n\x0fVehicleDynamics\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x35\n\x04\x65rrs\x18\x03 \x01(\x0b\x32\'.pb.SensorNearData.VehicleDynamics.Errs\x12;\n\x07signals\x18\x04 \x01(\x0b\x32*.pb.SensorNearData.VehicleDynamics.Signals\x12?\n\tvariances\x18\x05 \x01(\x0b\x32,.pb.SensorNearData.VehicleDynamics.Variances\x12@\n\ntimestamps\x18\x07 \x01(\x0b\x32,.pb.SensorNearData.VehicleDynamics.Timestamp\x1a\x86\x01\n\x04\x45rrs\x12;\n\x14steering_wheel_angle\x18\x07 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12\x41\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x1aK\n\x07Signals\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x02\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x02\x1aM\n\tVariances\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x02\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x02\x1aM\n\tTimestamp\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x12\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x12')
  ,
  dependencies=[header__pb2.DESCRIPTOR,SensorNearData_dot_SensorStates__pb2.DESCRIPTOR,])




_VEHICLEDYNAMICS_ERRS = _descriptor.Descriptor(
  name='Errs',
  full_name='pb.SensorNearData.VehicleDynamics.Errs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Errs.steering_wheel_angle', index=0,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Errs.steering_wheel_angle_speed', index=1,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=538,
)

_VEHICLEDYNAMICS_SIGNALS = _descriptor.Descriptor(
  name='Signals',
  full_name='pb.SensorNearData.VehicleDynamics.Signals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Signals.steering_wheel_angle', index=0,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Signals.steering_wheel_angle_speed', index=1,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=615,
)

_VEHICLEDYNAMICS_VARIANCES = _descriptor.Descriptor(
  name='Variances',
  full_name='pb.SensorNearData.VehicleDynamics.Variances',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Variances.steering_wheel_angle', index=0,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Variances.steering_wheel_angle_speed', index=1,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=694,
)

_VEHICLEDYNAMICS_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='pb.SensorNearData.VehicleDynamics.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.steering_wheel_angle', index=0,
      number=7, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.steering_wheel_angle_speed', index=1,
      number=8, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=696,
  serialized_end=773,
)

_VEHICLEDYNAMICS = _descriptor.Descriptor(
  name='VehicleDynamics',
  full_name='pb.SensorNearData.VehicleDynamics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.SensorNearData.VehicleDynamics.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errs', full_name='pb.SensorNearData.VehicleDynamics.errs', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signals', full_name='pb.SensorNearData.VehicleDynamics.signals', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variances', full_name='pb.SensorNearData.VehicleDynamics.variances', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='pb.SensorNearData.VehicleDynamics.timestamps', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VEHICLEDYNAMICS_ERRS, _VEHICLEDYNAMICS_SIGNALS, _VEHICLEDYNAMICS_VARIANCES, _VEHICLEDYNAMICS_TIMESTAMP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=773,
)

_VEHICLEDYNAMICS_ERRS.fields_by_name['steering_wheel_angle'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['steering_wheel_angle_speed'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS_SIGNALS.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS_VARIANCES.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS_TIMESTAMP.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS.fields_by_name['header'].message_type = header__pb2._HEADER
_VEHICLEDYNAMICS.fields_by_name['errs'].message_type = _VEHICLEDYNAMICS_ERRS
_VEHICLEDYNAMICS.fields_by_name['signals'].message_type = _VEHICLEDYNAMICS_SIGNALS
_VEHICLEDYNAMICS.fields_by_name['variances'].message_type = _VEHICLEDYNAMICS_VARIANCES
_VEHICLEDYNAMICS.fields_by_name['timestamps'].message_type = _VEHICLEDYNAMICS_TIMESTAMP
DESCRIPTOR.message_types_by_name['VehicleDynamics'] = _VEHICLEDYNAMICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleDynamics = _reflection.GeneratedProtocolMessageType('VehicleDynamics', (_message.Message,), dict(

  Errs = _reflection.GeneratedProtocolMessageType('Errs', (_message.Message,), dict(
    DESCRIPTOR = _VEHICLEDYNAMICS_ERRS,
    __module__ = 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Errs)
    ))
  ,

  Signals = _reflection.GeneratedProtocolMessageType('Signals', (_message.Message,), dict(
    DESCRIPTOR = _VEHICLEDYNAMICS_SIGNALS,
    __module__ = 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Signals)
    ))
  ,

  Variances = _reflection.GeneratedProtocolMessageType('Variances', (_message.Message,), dict(
    DESCRIPTOR = _VEHICLEDYNAMICS_VARIANCES,
    __module__ = 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Variances)
    ))
  ,

  Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), dict(
    DESCRIPTOR = _VEHICLEDYNAMICS_TIMESTAMP,
    __module__ = 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Timestamp)
    ))
  ,
  DESCRIPTOR = _VEHICLEDYNAMICS,
  __module__ = 'SensorNearData.VehicleDynamics_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics)
  ))
_sym_db.RegisterMessage(VehicleDynamics)
_sym_db.RegisterMessage(VehicleDynamics.Errs)
_sym_db.RegisterMessage(VehicleDynamics.Signals)
_sym_db.RegisterMessage(VehicleDynamics.Variances)
_sym_db.RegisterMessage(VehicleDynamics.Timestamp)


# @@protoc_insertion_point(module_scope)
