# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Applications/Truck/W3Lightbar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Applications/Truck/W3Lightbar.proto',
  package='pb.Applications.Truck',
  syntax='proto3',
  serialized_pb=_b('\n#Applications/Truck/W3Lightbar.proto\x12\x15pb.Applications.Truck\"\xe8\x01\n\x11W3LightbarRequest\x12\x11\n\ttake_down\x18\x02 \x01(\x08\x12\x18\n\x10\x61lley_light_left\x18\x03 \x01(\x08\x12\x19\n\x11\x61lley_light_right\x18\x04 \x01(\x08\x12\x19\n\x11red_warning_light\x18\x0c \x01(\x08\x12#\n\x1bthree_sixty_degree_colour_2\x18\x0e \x01(\x08\x12\x16\n\x0e\x66ront_colour_2\x18\x0f \x01(\x08\x12\x18\n\x10turn_signal_left\x18\x15 \x01(\x08\x12\x19\n\x11turn_signal_right\x18\x16 \x01(\x08\x62\x06proto3')
)




_W3LIGHTBARREQUEST = _descriptor.Descriptor(
  name='W3LightbarRequest',
  full_name='pb.Applications.Truck.W3LightbarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='take_down', full_name='pb.Applications.Truck.W3LightbarRequest.take_down', index=0,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alley_light_left', full_name='pb.Applications.Truck.W3LightbarRequest.alley_light_left', index=1,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alley_light_right', full_name='pb.Applications.Truck.W3LightbarRequest.alley_light_right', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='red_warning_light', full_name='pb.Applications.Truck.W3LightbarRequest.red_warning_light', index=3,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='three_sixty_degree_colour_2', full_name='pb.Applications.Truck.W3LightbarRequest.three_sixty_degree_colour_2', index=4,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_colour_2', full_name='pb.Applications.Truck.W3LightbarRequest.front_colour_2', index=5,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_signal_left', full_name='pb.Applications.Truck.W3LightbarRequest.turn_signal_left', index=6,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_signal_right', full_name='pb.Applications.Truck.W3LightbarRequest.turn_signal_right', index=7,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['W3LightbarRequest'] = _W3LIGHTBARREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

W3LightbarRequest = _reflection.GeneratedProtocolMessageType('W3LightbarRequest', (_message.Message,), dict(
  DESCRIPTOR = _W3LIGHTBARREQUEST,
  __module__ = 'Applications.Truck.W3Lightbar_pb2'
  # @@protoc_insertion_point(class_scope:pb.Applications.Truck.W3LightbarRequest)
  ))
_sym_db.RegisterMessage(W3LightbarRequest)


# @@protoc_insertion_point(module_scope)
