# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HMI/CanButton.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='HMI/CanButton.proto',
  package='pb.HMI',
  syntax='proto2',
  serialized_pb=_b('\n\x13HMI/CanButton.proto\x12\x06pb.HMI\x1a\x0cheader.proto\"\x9a\x01\n\x0b\x42uttonState\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x38\n\x10\x41\x63tStatForButton\x18\x02 \x01(\x0e\x32\x1e.pb.HMI.ButtonState.butstate_t\"5\n\nbutstate_t\x12\x13\n\x0f\x42UTTON_RELEASED\x10\x00\x12\x12\n\x0e\x42UTTON_CLICKED\x10\x01')
  ,
  dependencies=[header__pb2.DESCRIPTOR,])



_BUTTONSTATE_BUTSTATE_T = _descriptor.EnumDescriptor(
  name='butstate_t',
  full_name='pb.HMI.ButtonState.butstate_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUTTON_RELEASED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON_CLICKED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=147,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_BUTTONSTATE_BUTSTATE_T)


_BUTTONSTATE = _descriptor.Descriptor(
  name='ButtonState',
  full_name='pb.HMI.ButtonState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.HMI.ButtonState.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ActStatForButton', full_name='pb.HMI.ButtonState.ActStatForButton', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUTTONSTATE_BUTSTATE_T,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=200,
)

_BUTTONSTATE.fields_by_name['header'].message_type = header__pb2._HEADER
_BUTTONSTATE.fields_by_name['ActStatForButton'].enum_type = _BUTTONSTATE_BUTSTATE_T
_BUTTONSTATE_BUTSTATE_T.containing_type = _BUTTONSTATE
DESCRIPTOR.message_types_by_name['ButtonState'] = _BUTTONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonState = _reflection.GeneratedProtocolMessageType('ButtonState', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONSTATE,
  __module__ = 'HMI.CanButton_pb2'
  # @@protoc_insertion_point(class_scope:pb.HMI.ButtonState)
  ))
_sym_db.RegisterMessage(ButtonState)


# @@protoc_insertion_point(module_scope)
