# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/SurroundViewImage/SurroundViewImage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from SensorNearData import BaseImage_pb2 as SensorNearData_dot_BaseImage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorNearData/SurroundViewImage/SurroundViewImage.proto',
  package='pb.SensorNearData.SurroundViewImage',
  syntax='proto2',
  serialized_pb=_b('\n8SensorNearData/SurroundViewImage/SurroundViewImage.proto\x12#pb.SensorNearData.SurroundViewImage\x1a\x0cheader.proto\x1a\x1eSensorNearData/BaseImage.proto\"[\n\x11SurroundViewImage\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12*\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1c.pb.SensorNearData.BaseImage')
  ,
  dependencies=[header__pb2.DESCRIPTOR,SensorNearData_dot_BaseImage__pb2.DESCRIPTOR,])




_SURROUNDVIEWIMAGE = _descriptor.Descriptor(
  name='SurroundViewImage',
  full_name='pb.SensorNearData.SurroundViewImage.SurroundViewImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.SensorNearData.SurroundViewImage.SurroundViewImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.SensorNearData.SurroundViewImage.SurroundViewImage.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=234,
)

_SURROUNDVIEWIMAGE.fields_by_name['header'].message_type = header__pb2._HEADER
_SURROUNDVIEWIMAGE.fields_by_name['data'].message_type = SensorNearData_dot_BaseImage__pb2._BASEIMAGE
DESCRIPTOR.message_types_by_name['SurroundViewImage'] = _SURROUNDVIEWIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SurroundViewImage = _reflection.GeneratedProtocolMessageType('SurroundViewImage', (_message.Message,), dict(
  DESCRIPTOR = _SURROUNDVIEWIMAGE,
  __module__ = 'SensorNearData.SurroundViewImage.SurroundViewImage_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorNearData.SurroundViewImage.SurroundViewImage)
  ))
_sym_db.RegisterMessage(SurroundViewImage)


# @@protoc_insertion_point(module_scope)
